[versions]
kotlin = "1.6.10"
dagger = "2.40.5"
androidGradlePlugin = "7.0.4"
detekt = "1.19.0"
gradle = "4.0.1"
coroutines = "1.6.0"
androidx_core = "1.7.0"
androidx_cardivew = "1.0.0"
androidx_compat = "1.4.0"
androidx_preference = "1.1.1"
androidx_navigation = "2.3.5"
androidx_lifecycle = "2.4.0"
androidx_lifecycle_extensions = "2.2.0"
material = "1.4.0"
leak_canary = "2.7"
constraint_layout = "2.1.2"
retrofit = "2.9.0"
# CHECK FIX IN gradle.properties
moshi = "1.13.0"
# CHECK FIX IN gradle.properties
okhttp = "4.9.3"
espresso = "3.4.0"
support_runner = "1.4.0"
test_core_ktx = "1.4.0"
junit_ktx = "1.1.3"
okhttp3_idling_resource = "1.0.0"
mockito = "4.2.0"
mockito_kotlin = "4.0.0"
mockito_android = "3.8.0"
junit = "5.8.2"
truth = "1.1.3"
lint = "30.0.4"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dagger = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger"}
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref ="kotlin"}
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref ="kotlin"}
kotlin-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref ="coroutines"}

[bundles]
core = ["kotlin-stdlib-jdk8", "kotlin-reflect", "kotlin-kotlinx-coroutines-core"]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
versions = { id = "com.github.ben-manes.versions", version = "0.40.0" }
